/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresStoreIdIndexRouteImport } from './routes/stores.$storeId.index'
import { Route as StoresStoreIdReviewsNewRouteImport } from './routes/stores.$storeId.reviews.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdIndexRoute = StoresStoreIdIndexRouteImport.update({
  id: '/stores/$storeId/',
  path: '/stores/$storeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdReviewsNewRoute = StoresStoreIdReviewsNewRouteImport.update({
  id: '/stores/$storeId/reviews/new',
  path: '/stores/$storeId/reviews/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/saved': typeof SavedRoute
  '/stores/': typeof StoresIndexRoute
  '/stores/$storeId/': typeof StoresStoreIdIndexRoute
  '/stores/$storeId/reviews/new': typeof StoresStoreIdReviewsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/saved': typeof SavedRoute
  '/stores': typeof StoresIndexRoute
  '/stores/$storeId': typeof StoresStoreIdIndexRoute
  '/stores/$storeId/reviews/new': typeof StoresStoreIdReviewsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/saved': typeof SavedRoute
  '/stores/': typeof StoresIndexRoute
  '/stores/$storeId/': typeof StoresStoreIdIndexRoute
  '/stores/$storeId/reviews/new': typeof StoresStoreIdReviewsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guidelines'
    | '/saved'
    | '/stores/'
    | '/stores/$storeId/'
    | '/stores/$storeId/reviews/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guidelines'
    | '/saved'
    | '/stores'
    | '/stores/$storeId'
    | '/stores/$storeId/reviews/new'
  id:
    | '__root__'
    | '/'
    | '/guidelines'
    | '/saved'
    | '/stores/'
    | '/stores/$storeId/'
    | '/stores/$storeId/reviews/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuidelinesRoute: typeof GuidelinesRoute
  SavedRoute: typeof SavedRoute
  StoresIndexRoute: typeof StoresIndexRoute
  StoresStoreIdIndexRoute: typeof StoresStoreIdIndexRoute
  StoresStoreIdReviewsNewRoute: typeof StoresStoreIdReviewsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId/': {
      id: '/stores/$storeId/'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId/'
      preLoaderRoute: typeof StoresStoreIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId/reviews/new': {
      id: '/stores/$storeId/reviews/new'
      path: '/stores/$storeId/reviews/new'
      fullPath: '/stores/$storeId/reviews/new'
      preLoaderRoute: typeof StoresStoreIdReviewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidelinesRoute: GuidelinesRoute,
  SavedRoute: SavedRoute,
  StoresIndexRoute: StoresIndexRoute,
  StoresStoreIdIndexRoute: StoresStoreIdIndexRoute,
  StoresStoreIdReviewsNewRoute: StoresStoreIdReviewsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
