/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresStoreIdIndexRouteImport } from './routes/stores.$storeId.index'
import { Route as StoresStoreIdReviewsNewRouteImport } from './routes/stores.$storeId.reviews.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdIndexRoute = StoresStoreIdIndexRouteImport.update({
  id: '/stores/$storeId/',
  path: '/stores/$storeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdReviewsNewRoute = StoresStoreIdReviewsNewRouteImport.update({
  id: '/stores/$storeId/reviews/new',
  path: '/stores/$storeId/reviews/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/guidelines': typeof GuidelinesRoute
  '/operator': typeof OperatorRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/terms': typeof TermsRoute
  '/stores/': typeof StoresIndexRoute
  '/stores/$storeId/': typeof StoresStoreIdIndexRoute
  '/stores/$storeId/reviews/new': typeof StoresStoreIdReviewsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/guidelines': typeof GuidelinesRoute
  '/operator': typeof OperatorRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/terms': typeof TermsRoute
  '/stores': typeof StoresIndexRoute
  '/stores/$storeId': typeof StoresStoreIdIndexRoute
  '/stores/$storeId/reviews/new': typeof StoresStoreIdReviewsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/guidelines': typeof GuidelinesRoute
  '/operator': typeof OperatorRoute
  '/privacy': typeof PrivacyRoute
  '/saved': typeof SavedRoute
  '/terms': typeof TermsRoute
  '/stores/': typeof StoresIndexRoute
  '/stores/$storeId/': typeof StoresStoreIdIndexRoute
  '/stores/$storeId/reviews/new': typeof StoresStoreIdReviewsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/contact'
    | '/demo'
    | '/guidelines'
    | '/operator'
    | '/privacy'
    | '/saved'
    | '/terms'
    | '/stores/'
    | '/stores/$storeId/'
    | '/stores/$storeId/reviews/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/contact'
    | '/demo'
    | '/guidelines'
    | '/operator'
    | '/privacy'
    | '/saved'
    | '/terms'
    | '/stores'
    | '/stores/$storeId'
    | '/stores/$storeId/reviews/new'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/contact'
    | '/demo'
    | '/guidelines'
    | '/operator'
    | '/privacy'
    | '/saved'
    | '/terms'
    | '/stores/'
    | '/stores/$storeId/'
    | '/stores/$storeId/reviews/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  GuidelinesRoute: typeof GuidelinesRoute
  OperatorRoute: typeof OperatorRoute
  PrivacyRoute: typeof PrivacyRoute
  SavedRoute: typeof SavedRoute
  TermsRoute: typeof TermsRoute
  StoresIndexRoute: typeof StoresIndexRoute
  StoresStoreIdIndexRoute: typeof StoresStoreIdIndexRoute
  StoresStoreIdReviewsNewRoute: typeof StoresStoreIdReviewsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId/': {
      id: '/stores/$storeId/'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId/'
      preLoaderRoute: typeof StoresStoreIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId/reviews/new': {
      id: '/stores/$storeId/reviews/new'
      path: '/stores/$storeId/reviews/new'
      fullPath: '/stores/$storeId/reviews/new'
      preLoaderRoute: typeof StoresStoreIdReviewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  GuidelinesRoute: GuidelinesRoute,
  OperatorRoute: OperatorRoute,
  PrivacyRoute: PrivacyRoute,
  SavedRoute: SavedRoute,
  TermsRoute: TermsRoute,
  StoresIndexRoute: StoresIndexRoute,
  StoresStoreIdIndexRoute: StoresStoreIdIndexRoute,
  StoresStoreIdReviewsNewRoute: StoresStoreIdReviewsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
